version: '3'

services:
  cacti_db:
    image: mysql:latest
    container_name: cacti_db
    hostname: cacti_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      TZ: 'Asia/Tokyo'
    volumes:
      - ./cacti_db/server.cnf:/etc/mysql/conf.d/server.cnf:ro
      - ./cacti_db/tz.sh:/docker-entrypoint-initdb.d/tz.sh:ro
    ports:
      - "3306:3306"

  cacti_sv:
    build: ./cacti_sv
    container_name: cacti_sv
    hostname: cactia_sv
    restart: always
    volumes:
      - ./rra:/var/lib/cacti/rra
    environment:
      TZ: 'Asia/Tokyo'
    depends_on:
      - cacti_db

  cacti_web:
    build: ./cacti_web
    container_name: cacti_web
    hostname: cactia_web
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./rra:/var/lib/cacti/rra
    environment:
      TZ: 'Asia/Tokyo'
    depends_on:
      - cacti_db
      - cacti_sv
